# Generated by Django 3.2.6 on 2021-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
