# Generated by Django 3.2.6 on 2021-08-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notes_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='is_closed',
        ),
    ]
